- agent/src/twitter/prompts.ts
improved prompt to make it sound smarter. emphasize focus on taking facts from KB and deny agreeing if it doesn't know any facts. try offering reasonable solutions instead of long commentary. try make it not fall into dirty tricks.
> improve replies

- agent/src/twitter/execute.ts
increasing the limit for how many tweets we recurse for better contextual understanding for the really nested convos.
> increase tweet context window

- agent/src/temp/reply-testing.ts
- agent/src/twitter/execute.ts
if we do not find a bill then the vector search similarity distance need to be close. Can always tweak but on some testing it feels good
> tighten the vector search and improve prompt to reduce hallucinations

- agent/src/temp/reason-testing-twitter.ts
- agent/src/temp/update-prompt-db.ts
- agent/src/twitter/execute-interaction.ts
- agent/src/twitter/prompts.ts
This new layer will allow us to control how the content should sound on X and the step before ensures it is factually accurate.
> feat: multi-step response creation

- agent/package.json
- agent/src/twitter/execute-interaction.ts
- pnpm-lock.yaml
alternative for #74 we use GPT-4o to test and see quality.
> remove opus for now

- agent/src/api/test-engage.ts
- agent/src/api/test-reply.ts
- dashboard/src/components/Settings.astro
- dashboard/src/components/engagement.tsx
- dashboard/src/components/reply.tsx
> dashboard fixes

- agent/package.json
- agent/src/api/test-engage.ts
- agent/src/api/test-reply.ts
- agent/src/logger.ts
- agent/src/server.ts
- agent/src/temp/engage-twitter.ts
- agent/src/temp/reply-twitter.ts
- agent/src/twitter/execute-interaction.ts
- agent/src/twitter/execute.ts
- agent/src/twitter/helpers.ts
- agent/src/twitter/ingest-interaction.ts
- agent/src/twitter/ingest.ts
- agent/src/twitter/process-interactions.ts
- agent/src/twitter/process.ts
- pnpm-lock.yaml
I noticed[ fly already has a Grafana dashboard](https://fly.io/docs/monitoring/logging-overview/) for logs that they preserve so setting up [pino](https://github.com/pinojs/pino) should give us more structured logging.
> logging improvements

- agent/package.json
- agent/src/discord/action.ts
- agent/src/temp/reply-twitter.ts
- agent/src/twitter/execute.ts
- agent/src/twitter/helpers.ts
- agent/src/twitter/process.ts
Use `sonar-reasoning` for replies and make it reply to any reply he gets.
> feat: engage in replies

- agent/package.json
- agent/src/inngest.ts
- agent/src/temp/reply-twitter.ts
- agent/src/temp/tag-twitter.ts
- agent/src/twitter/execute.ts
- agent/src/twitter/process-interactions.ts
- agent/src/twitter/process.ts
- agent/src/twitter/prompts.ts
Allow tagging for a question for DOGEai to respond back to.
> feat: tagging for questions

- agent/src/api/test-reply.ts
- agent/src/discord/action.ts
- agent/src/discord/client.ts
- agent/src/temp/reply-twitter.ts
- agent/src/temp/tag-twitter.ts
- agent/src/twitter/execute.ts
- agent/src/twitter/process-interactions.ts
- agent/src/twitter/prompts.ts
also increases recursion for tweet context
> feat: refinement layer for question/answer layer

- agent/package.json
- agent/src/twitter/execute-interaction.ts
- pnpm-lock.yaml
Another attempt to make these long replies short and engaging.
> feat: making replies short and fun

- agent/src/temp/engage-twitter.ts
- agent/src/temp/reply-twitter.ts
- agent/src/twitter/execute-interaction.ts
- agent/src/twitter/execute.ts
- agent/src/twitter/helpers.ts
- agent/src/twitter/prompts.ts
Introduce a new layer who's job is to structure the tweet better so it is not a giant block of text.
> feat: formatter for long style tweets

- agent/src/api/test-reply.ts
- agent/src/temp/reply-twitter.ts
- agent/src/temp/tag-twitter.ts
- agent/src/twitter/execute.ts
closes https://github.com/saihaj/DOGE-AI/issues/91
> fix: repetition in follow ups

- dashboard/src/app/chat.tsx
- dashboard/src/components/ui/autosize-textarea.tsx
https://github.com/user-attachments/assets/d2b02c54-a01f-47d8-a182-0939deee7a97
closes #109
> feat: multi-line chat input with keyboard shortcuts

- agent/src/server.ts
- dashboard/package.json
- dashboard/src/app/chat.tsx
- pnpm-lock.yaml
https://github.com/user-attachments/assets/4c685270-b3ef-4297-9216-063f05a3bbeb
closes #110
> feat: tweet extraction in chat

- dashboard/src/app/chat.tsx
https://github.com/user-attachments/assets/4a0f08b5-43f2-44d6-9590-f204f2d0ae3e
closes #111
> feat: template variable support

- agent/src/twitter/ingest-interaction.ts
- agent/src/twitter/ingest.ts
closes https://github.com/saihaj/DOGE-AI/issues/123
> fix: account for ingestor errors

- agent/src/twitter/knowledge-base.ts
> fix: improve contextual matching

- agent/src/api/prompt.ts
- agent/src/server.ts
- agent/src/twitter/prompts.ts
- dashboard/package.json
- dashboard/src/app/prompts/page.tsx
- dashboard/src/app/prompts/validator.ts
- dashboard/src/components/app-sidebar.tsx
- pnpm-lock.yaml
https://github.com/user-attachments/assets/318c8417-676f-422b-a638-8866e9f4b755
Give a text editor view for all the different prompts we have in production. For any variables it ensures certain format is followed before publishing and backend will ensure any mismatch in variables. 
closes https://github.com/saihaj/DOGE-AI/issues/114
> feat: deploying prompts from UI

- agent/package.json
- agent/src/api/chat.ts
- agent/src/const.ts
- agent/src/server.ts
- agent/src/twitter/web.ts
- dashboard/src/app/chat.tsx
- pnpm-lock.yaml
> feat: web searching

- agent/src/api/chat.ts
- dashboard/src/components/model-selector.tsx
> feat: llama4 models

- agent/src/twitter/execute-interaction.ts
- agent/src/twitter/execute.ts
not being used anywhere so far in last 2 months. We can always embed in batch in future if/when needed.
> remove vectorizing of chat messages

- agent/src/api/test-reply.ts
- agent/src/temp/reply-twitter.ts
- agent/src/twitter/execute.ts
- agent/src/twitter/helpers.ts
- agent/src/twitter/prompts.ts
Refactor question extractor and move to `4o-mini` it performs the same as `4o` in the usage here so why not just use an cost effective model.
> refactor & optimization

- agent/package.json
- agent/src/api/chat.ts
- agent/src/const.ts
- agent/src/twitter/execute-interaction.ts
- pnpm-lock.yaml
> feat: setup deepinfra

- agent/src/server.ts
- dashboard/src/app/userchat/chat.tsx
- dashboard/src/components/ui/badge.tsx
- pnpm-lock.yaml
Part of the new user chat interface it is hard to tell if KB was used or not. This PR adds a UI annotation if KB was used in the context
> feat: show if KB was used in context or not

- agent/package.json
- agent/src/api/chat.ts
- agent/src/const.ts
- dashboard/src/components/model-selector.tsx
- pnpm-lock.yaml
> feat: add gemini models

- agent/src/server.ts
- agent/src/temp/update-prompt-db.ts
- agent/src/twitter/prompts.ts
- chat/next.config.ts
- chat/package.json
- chat/src/app/layout.tsx
- chat/src/app/page.tsx
- chat/src/components/hooks/use-cookie.tsx
- chat/src/components/ui/sonner.tsx
- chat/src/lib/const.ts
- pnpm-lock.yaml
temporary setup where it proxies request back to agent API endpoint. Need to figure out best way to scale this but for testing should be good.
> feat: setup streaming for chat interface

- agent/package.json
- agent/src/api/manual-kb.ts
- agent/src/api/test-engage.ts
- agent/src/const.ts
- agent/src/server.ts
- agent/src/temp/engage-twitter.ts
- agent/src/temp/fork-agent-kb.ts
- agent/src/twitter/execute-interaction.ts
- agent/src/twitter/knowledge-base.ts
- dashboard/src/app/manual-kb/page.tsx
- dashboard/src/app/manual-kb/type-selector.tsx
- **refactor: rename agent kb entries var**
- **feat: split out kb vs chat kb**
- **fork kb entries**
- **update query**
> feat: segment manual kb for chat

- chat/package.json
- chat/src/app/globals.css
- chat/src/app/not-found.tsx
- chat/src/app/page.tsx
- pnpm-lock.yaml
- **feat: add 404 page**
- **prefetch**
> feat: 404 page

- agent/src/chat-server.ts
- agent/src/utils/stream.ts
this service is private in cluster so only Envoy can make calls which is going to provider the right headers.
> refactor: utilize envoy provided values

- agent/src/chat-api/router.ts
- agent/src/chat-server.ts
- chat/src/app/chat/[id]/page.tsx
- chat/src/app/page.tsx
- **improve prompt suggestion on mobile**
- **handle chat not found state**
- **debug**
> mobile improvements

- website/components/benefits-grid/BenefitsGrid.tsx
- website/components/shared/SectionHeading.tsx
- website/components/shared/SectionSubheading.tsx
- website/components/stats/Stats.tsx
- website/pages/index.tsx
- website/pages/interactions.tsx
- website/pages/white-label.tsx
- **fix: interactions page header**
- **fix: updates to homepage**
- **fix: white label page updates**
> site updates

- agent/src/chat-server.ts
- agent/src/const.ts
- agent/src/twitter/prompts.ts
- dashboard/src/app/api/restart/route.ts
- envoy/envoy.template.yaml
- **feat: demo testing api**
- **fix cors**
> feat: demo api for user chat

- dashboard/package.json
- dashboard/src/app/chat.tsx
- dashboard/src/app/userchat/chat.tsx
- pnpm-lock.yaml
https://github.com/user-attachments/assets/fae5ec32-4590-4fef-a799-475d22d676c7
> feat: dynamic avatars for playground chat
